import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getCookie from '../lib/cookie.js'
import { useState, useEffect } from 'react'

export default function Home() {
  const [status, setStatus] = useState('loading');
  const [accessToken, setAccessToken] = useState('');
  useEffect(() => {
    (async () => {
      let cookie = await fetch('/api/token').then(res => res.text());
      alert(cookie);
      if (cookie) {
        setAccessToken(cookie);
        setStatus('authed');
      } else {
        setStatus('unauthed');
      }
    })();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Assemble Preflight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {status == 'authed' && <main className={styles.main}>
        <h1 className={styles.title}>
          {status} Welcome to <a href="/login">Login</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>{accessToken}</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>}

      {status == 'unauthed' && <main className={styles.main}>
        <h1 className={styles.title}>
          Assemble Preflight
        </h1>

        <div className={styles.grid}>
          <a href="/login" className={styles.card} style={{ minHeight: '250px' }}>
            <h2>Web &rarr;</h2>
            <p>Sign in to start the preflight & vaccine verification process in your browser.</p>
          </a>
          <a href="assembleticketing://checkin" className={styles.card} style={{ minHeight: '250px' }}>
            <h2>iOS App &rarr;</h2>
            <p>Download the iOS app for preflight, vaccine verification, and real-time event integration.</p>
          </a>
        </div>
      </main>}

      {status == 'loading' && <main className={styles.main}>
        <h1 className={styles.title}>
          Assemble Preflight
        </h1>

        <div className={styles.grid}>
          Please wait...
        </div>
      </main>}

      <footer className={styles.footer}>
        <span>
          Hack Club Assemble | Everything open source at{' '}
          <a
            href="https://github.com/hackclub/assemble"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: 'red' }}
          >
            hackclub/assemble
          </a>
        </span>
      </footer>
    </div>
  )
}
